import noticePdf from '../fakeData/PDF/notice.pdf';
const noticeData = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet',
        file_type: 'pdf',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        fullDetails: noticePdf,
        authorName: 'Maxime',
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
    {
        id: 2,
        title: 'Lorem ipsum dolor sit amet',
        file_type: '',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        fullDetails: noticePdf,
        authorName: 'Maxime',
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
    {
        id: 3,
        file_type: '',
        title: 'Lorem ipsum dolor sit amet',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        fullDetails: noticePdf,
        authorName: 'Maxime',
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
    {
        id: 4,
        file_type: '',
        title: 'Lorem ipsum dolor sit amet',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        fullDetails: noticePdf,
        authorName: 'Maxime',
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
    {
        id: 5,
        file_type: '',
        title: 'Lorem ipsum dolor sit amet',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        authorName: 'Maxime',
        fullDetails: noticePdf,
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
    {
        id: 6,
        file_type: '',
        title: 'Lorem ipsum dolor sit amet',
        noticeDetails: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum repellat delectus deleniti at dignissimos neque fuga mollitia dolor autem ipsam?',
        fullDetails: noticePdf,
        authorName: 'Maxime',
        image: '"https://www.lawcolumn.in/ezoimgfmt/i0.wp.com/www.lawcolumn.in/wp-content/uploads/2021/05/263x166-notice-263x166.jpg?fit=263%2C166&ssl=1&is-pending-load=1&ezimgfmt=rs:263x166/rscb29/ng:webp/ngcb29"',
        date: new Date().toLocaleDateString(),
    },
];
export default noticeData;
